const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Demo',
      description: 'Demo',
    },
  ],
  securityDefinitions: {
    bearerAuth: {
      name: 'Authorization', // name of the header, query parameter or cookie
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      description: 'Enter JWT Bearer Token.',
    },
  },
  definitions: {
  },
};

const outputFile = 'router/swagger.json';
const endpointsFiles = [
  'router/index.js',
];

swaggerAutogen(outputFile, endpointsFiles, doc);
